---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unifi-bouncer
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  maxHistory: 2
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      unifi-bouncer:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/shockstruck/cs-unifi-bouncer
              tag: v1.0.3@sha256:285e6152395fabe4723541befad80f2d5368726cc9e5378931e1fdfe06d6fe55
            env:
              TZ: ${TIMEZONE}
              LOG_LEVEL: info
              CROWDSEC_URL: "https://crowdsec-service.security.svc.cluster.local:8080"
              CROWDSEC_BOUNCER_API_KEY: ${CROWDSEC_UNIFI_BOUNCER_KEY}
              CROWDSEC_ORIGINS: "crowdsec cscli csccli-import console CAPI lists"
              CROWDSEC_UPDATE_INTERVAL: 30s
              UNIFI_HOST: "https://10.1.255.254"
              UNIFI_SKIP_TLS_VERIFY: true
              UNIFI_SITE: default
              UNIFI_MAX_GROUP_SIZE: "10000"
              UNIFI_ZONE_SRC: "External Internal Vpn Hotspot Cameras IoT WLAN"
              UNIFI_ZONE_DST: "Internal External Vpn Gateway Hotspot Cameras IoT Servers MGMT WLAN"
              UNIFI_POLICY_REORDERING: true
              UNIFI_LOGGING: false
              UNIFI_LOG_CLEANUP: false
              UNIFI_LOG_CLEANUP_MINUTES: "5"
              SSL_CERT_FILE: /etc/ssl/certs/crowdsec-ca.crt
            envFrom:
              - secretRef:
                  name: unifi-bouncer-secret

            
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 15m
                memory: 768Mi
              limits:
                memory: 1Gi
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
            fsGroup: 65532
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile: { type: RuntimeDefault }
    persistence:
      crowdsec-ca:
        type: secret
        name: crowdsec-root-secret
        globalMounts:
          - path: /etc/ssl/certs/crowdsec-ca.crt
            subPath: ca.crt
            readOnly: true